Added clearing whitespace when converting header string to array
labrador-kennel/http-cors pull request #32
Opened 2021-05-27 07:58 UTC by kadarsys

Hello. Faced a bug when passing multiple headers in an OPTIONS request. The bug was found only in IE 11. I fixed it. Please see PR

2021-05-27 12:09 UTC, cspray requested changes
Hi! Thank you for submitting this fix. I made some comments on minor adjustments that should be made. Once the changes have been put in place I'll be happy to merge this in.

2021-05-27 12:09 UTC, cspray commented on .gitignore
> +/phpunit.xml
I don't believe the phpunit file should be added to ignore.

2021-05-27 12:09 UTC, cspray commented on composer.json
> +    "php": "^7.0",
I don't want to exclude PHP8 installs. Please update to "^7.0 || ^8.0"

2021-05-28 06:58 UTC, kadarsys commented on .gitignore
> +/phpunit.xml
Oк. But I would think that if the git index contains phpunit.xml.dist, then it should be excluded from the index.  This is not true?

2021-05-28 13:43 UTC, cspray commented on .gitignore
> +/phpunit.xml
That's a fair point. The `.dist` is actually a legacy artifact from how I was setting up most of my projects. I would actually prefer to see the `phpunit.xml.dist` file renamed to `phpunit.xml`. We can then remove this from `.gitignore`. No other changes should be necessary.

2021-06-01 07:00 UTC, kadarsys commented on .gitignore
> +/phpunit.xml
Ok

2021-06-01 20:50 UTC, cspray approved these changes

2021-06-01 20:51 UTC, merged

2021-06-01 20:51 UTC, cspray commented
Thank you for submitting your PR @kadarsys! I want to make some changes to my CI setup to properly test 7.x and 8.x versions. After that I will cut a new bug fix release with your additions.